models:
  - name: wood_cube_10cm
    type: sdf
    package: object_spawner
    pose: [1.2, 0, 0, 0, 0, 0]
  - name: wood_cube_10cm
    type: sdf
    package: object_spawner
    pose: [1.1, 0, 0, 0, 0, 0]
  - name: wood_cube_10cm
    type: sdf
    package: object_spawner
    pose: [0.9, 0, 0, 0, 0, 0]
  - name: wood_cube_10cm
    type: sdf
    package: object_spawner
    pose: [1.0, 0, 0, 0, 0, 0]
  - name: wood_cube_10cm
    type: sdf
    package: object_spawner
    pose: [0.7, 0, 0, 0, 0, 0]
  - name: wood_cube_10cm
    type: sdf
    package: object_spawner
    pose: [0.8, 0, 0, 0, 0, 0]

